### ISSUE TITLE
[Enhancement] Recommended workflow

### ISSUE THREAD

**Issue by micky2be** [stevemao/conventional-changelog-cli#11]
In the following workflow people could combine 4 to 7 with a simple hook.
https://github.com/conventional-changelog-archived-repos/conventional-changelog-cli#recommended-workflow

With this hook people could simply use `npm version`
```json
{
  "scripts": {
    "version": "conventional-changelog -p angular -i CHANGELOG.md -s -r 0 && git add CHANGELOG.md"
  }
}
```

If you combine with a proper `.npmrc`the workflow could become:

1. Make changes
2. Commit those changes
3. Make sure Travis turns green
4. Bump version with `npm version <patch|minor|major>` command
5. Push

**Comment by stevemao** [comment]
I didn't know about the version hook. CC @bcoe @Tapppi 
This might improve the workflow of `standard-changelog`?

**Comment by micky2be** [comment]
The good thing about it is if you also have a `preversion` and a `postversion` scripts.
Where a `preversion` could run test and a `postversion` push to github and/or publishing to npm.
Making the whole workflow of release very simple.

**Comment by stevemao** [comment]
@micky2be feel free to send a PR against the monorepo https://github.com/conventional-changelog/conventional-changelog :)

**Comment by micky2be** [comment]
What would be your suggestion?
Replacing the current recommended workflow or add it as an alternative?

**Comment by stevemao** [comment]
@micky2be just replace it

**Comment by hutson** [comment]
We're closing this issue out as this repository has been merged into our [`conventional-changelog`](https://github.com/conventional-changelog/conventional-changelog) mono-repository.

If you would like to see this change incorporated into `conventional-changelog` please consider re-opening the issue against the `conventional-changelog` mono-repository.
