### ISSUE TITLE
Append top of the file

### ISSUE THREAD

**Issue by Kikobeats** [stevemao/conventional-changelog-cli#2]
Currently is append on the bottom of the changelog file :(

First I do:

```
conventional-changelog --preset=angular -infile=CHANGELOG.md --same-file --release-count=0
```

later I release a new tag and:

```
conventional-changelog --preset=angular -infile=CHANGELOG.md -a -s
```

**Comment by stevemao** [comment]
have you tried

```
conventional-changelog --preset=angular --infile=CHANGELOG.md --same-file --release-count=0 -a
```

**Comment by Kikobeats** [comment]
But I want to add an incremental tag from the base file

On Thursday, 24 March 2016, Steve Mao notifications@github.com wrote:

> have you tried
> 
> conventional-changelog --preset=angular -infile=CHANGELOG.md --same-file --release-count=0 -a
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/stevemao/conventional-changelog-cli/issues/2#issuecomment-200577125

## 

_Att, Kiko._

**Comment by stevemao** [comment]
Yes, but if you wanna use append option you should append releases from the beginning. 

> Currently is append on the bottom of the changelog file :(

This is the expected behaviour?

**Comment by Kikobeats** [comment]
When you read a changelog file you read it from top to bottom; from the
last release to the first realise.

Don't have sense append last release at the end of the file.

On Thursday, 24 March 2016, Steve Mao notifications@github.com wrote:

> Yes, but if you wanna use append option you should append releases from
> the beginning.
> 
> Currently is append on the bottom of the changelog file :(
> 
> This is the expected behaviour?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/stevemao/conventional-changelog-cli/issues/2#issuecomment-200591535

## 

_Att, Kiko._

**Comment by stevemao** [comment]
That's why 99.99% of the time you don't need to use append. Why do you use append then?

**Comment by Kikobeats** [comment]
But then how to write the new tag in the file?

On Thursday, 24 March 2016, Steve Mao notifications@github.com wrote:

> That's why 99.99% of the time you don't need to use append. Why do you use
> append then?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/stevemao/conventional-changelog-cli/issues/2#issuecomment-200593170

## 

_Att, Kiko._

**Comment by stevemao** [comment]
if you don't specify append, it by default prepends to the file.

**Comment by Kikobeats** [comment]
Oh, it's true. Now works good :+1:

PS: I'm integrating changelog with a [bumped plugin](https://github.com/bumped/bumped-changelog)
