### ISSUE TITLE
1.1.1 and 1.0.1 change of behavior

### ISSUE THREAD

**Issue by silkentrance** [stevemao/conventional-changelog-cli#3]
I find it strange for a rather "simple" tool to change its general behavior between minor releases, e.g. switching from `-w` to `-s` and now requiring `-p <preset>` in order to be able to get an expected result when using `conventional-changelog`.

While I appreciate you all doing a great job in providing this tool, it would be nice of you for at least keep a reasonable default when breaking with existing behavior.

The most reasonable defaults would have been
- aliasing `-w` with `-s`
- using a default preset `-p angular`

TIA

**Comment by stevemao** [comment]
> using a default preset -p angular

Use https://github.com/stevemao/standard-changelog

**Comment by silkentrance** [comment]
@stevemao thanks for the pointer, is there some docs/blog about this?

**Comment by stevemao** [comment]
Fixed. Thanks for the suggestion :)
