### ISSUE TITLE
--config does not work with recent version of angular/config.js and so on (and here is why)

### ISSUE THREAD

**Issue by FGRibreau** [stevemao/conventional-changelog-cli#9]
Latest version of changelog-cli wants an exported object

``` js
if (flags.config) {
    config = require(resolve(process.cwd(), flags.config));
  } else {
    config = {};
  }
// [...]

var changelogStream = conventionalChangelog(options, templateContext, config.gitRawCommitsOpts, config.parserOpts, config.writerOpts)
```

while latest config version of [conventional-changelog-angular](https://github.com/conventional-changelog/conventional-changelog-angular) exports a promise and other versions a callback. 

That's why the conventional-changelog library works with these configuration files but not the CLI.

**Comment by hutson** [comment]
We're closing this issue out as this repository has been merged into our [`conventional-changelog`](https://github.com/conventional-changelog/conventional-changelog) mono-repository.

If you would like to see this change incorporated into `conventional-changelog` please consider re-opening the issue against the `conventional-changelog` mono-repository.
